id: P01B55481
initial_creation_type: input
source_metadata:
  title: Dharma Protectors Series
  language: fr
  description: 'The following texts are now available as part of our Dharma Protectors
    (dharmapāla; Tib. chos skyong) series:'
  volume:
    c51c360ccde8470194852e6a8c04fa35:
      title: Brief Dharmapālas Offering
      parent: General
    c7452f1b6b0940eb9b8f45423692d1bb:
      title: Brief Protectors Practice
      parent: General
    9ada6647591140519f62bfd806f77fd2:
      title: Expeditious Activity Torma Offering
      parent: General
    a56c20ba406c4b8a93db6c6102d8960c:
      title: Wayfaring Offering
      parent: General
    62ea21ba986742eb94698c442bf2732b:
      title: A Practice of Fulfilment and Confession to an Ocean of Oath-bound Protectors
      parent: General
    02f75109f90d44a0aef98a39bfad9dee:
      title: 'Damchen Chitor: A Brief Practice of Torma Offering to the Oath-Bound
        Guardians'
      parent: General
    815f259638ac4f9e92bb442a3dc6bad3:
      title: Offering Prayer to Changshönma, Protectress Riding upon a Wolf
      parent: Changshönma
    31f80d8200fb40f28304be40d78c189c:
      title: Brief Offering Prayer to Durtrö Lhamo, Mistress of the Charnel Ground
      parent: Durtrö Lhamo
    a1753705cbc94f808f76f00f1184c583:
      title: Golden Drink (Serkyem) and Torma Offering
      parent: Eight Classes
    e5e5bc308ece4f9bba77f1900062b398:
      title: Restorative Offering to the Eight Classes
      parent: Eight Classes
    72aacc2f39d04958b845628ff23fd521:
      title: Brief Offering Prayer to Ekajaṭī
      parent: Ekajaṭī
    97bdf4d251eb4a3ba8ea90cd68f8b689:
      title: Offering to the Five Medicine Sisters, Guardians of the Earth
      parent: Five Medicine Sisters
    1f6949e95deb43689e0b66ac16663071:
      title: Petitionary Offering to Norbu Dradül Tsal
      parent: Gesar
    9fe6e60219b648e48e7732256194f7de:
      title: Brief Offering Prayer to Gesar
      parent: Gesar
    b67b401a6ae0495f80d2c259b992fc1a:
      title: 'Sweet Melody to Delight the Glorious Deity: In Praise of Śrī Kālīdevī'
      parent: Kālīdevī
    f33f9f390e914281816b7eafb5ce2228:
      title: 'Swift Enlightened Activity: A Concise Ceremony of Offering and Prayer
        to Mahākāla and Consort'
      parent: Mahākāla
    c3d048c03e704efeadb6434766072758:
      title: 'The Fulfilment of All Wishes: Prayer and Entrustment of Activity to
        the Glorious Guru Mahākāla Pañjaranātha'
      parent: Mahākāla
    3fda37086b204440bf6f652782f1056d:
      title: 'Bestower of Supreme Accomplishment: A Torma Offering to Mahākāla'
      parent: Mahākāla
    2eabaf27a31d4a05a88924120d3903f7:
      title: 'Pacifying the Turmoil of the Mamos: A Concise Liturgy'
      parent: Pacifying the Turmoil of the Mamos
    263006c4a35a44ea9e82a76afe8fffb1:
      title: Brief Prayer for Pacifying the Turmoil of the Mamos
      parent: Pacifying the Turmoil of the Mamos
    40eb5f4749724ccb8f76f8ba262bf9d8:
      title: A Brief Petitionary Offering to the Mātṛkā Pukkasī, Local Protectress
        of the Jarung Kashor Stūpa
      parent: Pukkasī
    3fadfd378a65441cb8384c1370855af1:
      title: Brief Offering Prayer to Za Rāhula
      parent: Rāhula
    b029ed712c904303a45daa80e8561982:
      title: Serkyem (Golden Libation) Offering to the Guardians of the Tradition
      parent: Serkyem
    8efa97a44ef04d43a2958900e7be4fb9:
      title: Brief Offering Prayer to Tsiu Marpo
      parent: Tsiu Marpo
    7abfb1e8a1e244189cb7df4184412f4f:
      title: Brief Offering Prayer to the Oath-Bound Vajrasādhu
      parent: Vajrasādhu
    2398e93435934035acf1ed748785ab77:
      title: Yarlha Shampo Sang Offering
      parent: Yarlha Shampo
created_at: '2022-03-01T03:27:20.282742'
last_modified_at: '2022-03-01T03:27:20.282745'
